name: Dev Deploy

on:
  workflow_dispatch:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build 🔧
        run: npm ci && npm run build --if-present
      - name: Moves into dev folder 📂
        run: mkdir dev && mv public dev -i
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          base_branch: dev
          branch: gh-pages
          folder: dev
          clean: true
          clean-exclude: |
            CNAME
            README.md
            public
            index.html
            favicon.png
            global.css
